version: "3.8"

services:
  db:
    image: postgres:15
    container_name: pg-earthquake
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthquakes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  etl:
    build: .
    container_name: etl-earthquake
    depends_on:
      - db
    volumes:
      - .:/app
      - ./data:/app/data
    working_dir: /app
    command: python main.py

volumes:
  postgres_data:
